### ISSUE TITLE
Latest version not working with helix

### ISSUE THREAD

**Issue by beeb** [JoranHonig/tree-sitter-solidity#68]
I'm trying to update helix to use the latest version of this grammar and I get a parsing error.

Steps to reproduce:

- Install helix 25.01
- Inside `~/.config/helix/languages.toml` add the following:

```toml
[[grammar]]
name = "solidity"
source = { git = "https://github.com/JoranHonig/tree-sitter-solidity", rev = "f7f5251a3f5b1d04f0799b3571b12918af177fc8" }
```

- `hx --grammar fetch`
- `hx --grammar build`
- open a solidity project with helix
- `:log-open` to show the helix logs
- observe the error: `helix_core::syntax [ERROR] Could not parse queries for language "solidity". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 212, column: 3, offset: 3935, message: "", kind: NodeType }`
